tvshowcountdown/tvshow/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.search, name='index'),
    url(r'^search$', views.search, name='search'),
    url(r'^info/(?P<slug_id>[a-zA-Z0-9\-]+)$', views.info, name='info'),
    url(r'^shows$', views.shows, name='shows')
]

tvshowcountdown/tvshowcountdown/urls.py
from django.views.generic.base import RedirectView

"""tvshowcountdown URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^tvshow/.*', include('tvshow.urls', namespace="tvshow")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^.*$', RedirectView.as_view(url='^tvshow/', permanent=False))
]

tvshowcountdown/tvshow/models.py
from django.db import models

# Create your models here.

tvshowcountdown/tvshow/views.py
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse

from . import trakt

import dateutil.parser


def search(request):
    context = {}
    if "search_term" in request.GET:
        return handle_search(request)
    return render_to_response('index.html', context)


def handle_search(request):
    context = {}
    if request.GET["search_term"] == "":
        context["error_message"] = "Can't search with an empty field."
    else:
        context["search_results"] = trakt.search(request.GET["search_term"])
        context["search_term"] = request.GET["search_term"]

    if request.GET.get("add_show", None) is not None:
        added = False
        user_shows = request.session.get("user_shows", None)
        if user_shows:
            user_shows = user_shows.split(',')
            show_to_add = request.GET["add_show"]
            if show_to_add not in user_shows:
                user_shows.append(show_to_add)
                added = show_to_add
            else:
                context["warning_message"] = "You already have {} in your collection".format(show_to_add)
            user_shows = ','.join(user_shows)
        else:
            user_shows = request.GET["add_show"]
            added = user_shows


        request.session["user_shows"] = user_shows
        if added:
            context["success_message"] = "Added {} to your collection".format(added)
    return render_to_response('index.html', context)


def info(request, slug_id):
    context = {}
    episode = trakt.get_next_episode(slug_id)
    show = trakt.get_show(slug_id)
    if episode == None or episode['first_aired'] is None:
        context["error_message"] = "Could not get next episode"
    else:
        timestamp = episode['first_aired']
        time_later = dateutil.parser.parse(timestamp)
        countdown_timer = {}
        countdown_timer["year"] = time_later.year
        countdown_timer["month"] = time_later.month - 1 # Because js counts months from 0
        countdown_timer["day"] = time_later.day
        countdown_timer["hour"] = time_later.hour
        countdown_timer["minute"] = time_later.minute
        countdown_timer["second"] = time_later.second
        context["countdown_timer"] = countdown_timer
        show_info = {}
        show_info["episode_title"] = episode["title"]
        show_info["season"] = episode["season"]
        show_info["episode_number"] = episode["number"]
        show_info["show_title"] = show["title"]
        show_info["image"] = show["images"]["banner"]["full"]
        context["show_info"] = show_info
        print(show)
    return render_to_response('info.html', context)


def shows(request):
    context = {}
    user_shows = request.session.get("user_shows", None)
    if user_shows:
        user_shows = user_shows.split(',')
        users_shows = []
        for show in user_shows:
            users_shows.append(trakt.get_show(show))
        context['users_shows'] = users_shows
    return render_to_response('shows.html', context)

tvshowcountdown/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <title>TV countdown</title>

    <!-- Bootstrap core CSS -->
    {% load staticfiles %}
    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet">


  </head>
<!-- NAVBAR
================================================== -->
  <body>
    <div class="navbar-wrapper" bgcolor='black'>
      <div class="container">

        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">TV Show countdown</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'tvshow:index' %}">Home</a></li>
                <li class="active"><a href="{% url 'tvshow:shows' %}">My Shows</a></li>
              </ul>
            </div>
          </div>
        </nav>

        {% block body %}
        {% endblock %}

        {% if error_message %}
          <div class="alert alert-danger"> {{ error_message }} </div>
        {% endif %}
        
        {% if success_message %}
          <div class="alert alert-success" role="alert">{{ success_message }}</div>
        {% endif %}
        
        {% if warning_message %}
          <div class="alert alert-warning" role="alert">{{ warning_message }}</div>
        {% endif %}
        
        {% block content %}
        {% endblock %}

      </div>
    </div>
  </body>
</html>

tvshowcountdown/templates/base_search_bar.html
{% extends 'base.html' %}

{% block body %}
<form class="text-center" action="{% url 'tvshow:search' %}" method="get">
    <div class="row">
        <div class="input-group form-inline col-md-6 col-md-offset-3">
            <input name="search_term" type="text" class="form-control" placeholder="Search" value="{{ search_term }}" autofocus>
            <span class="input-group-btn">
              <button type="submit" class="btn btn-default">Search</button>
          </span>
        </div>
    </div>
</form>
<br>

{% endblock %}

tvshowcountdown/tvshow/templates/index.html
{% extends 'base_search_bar.html' %}
{% block content %}

{% if search_results %}
  <script src=/static/js/sorttable.js></script>
  <div class="panel panel-default">
    <div class="panel-heading">Search results</div>
    <table class="table sortable">
      <thead>
        <tr>
          <th>Name</th>
          <th>Year</th>
          <th class="sorttable_nosort">Add</th>
        </tr>
      </thead>
      <tbody>
        {% for result in search_results %}
        <tr>
          <th><a href="{% url 'tvshow:info' result.slug %}">{{ result.name }}</a></th>
          <th>{{ result.year }}</th>
          <th><a href="{% url 'tvshow:search' %}?search_term={{ search_term }}&add_show={{ result.slug}}"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a></th>
        <tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endif %}

{% endblock %}

tvshowcountdown/tvshow/templates/info.html
{% extends 'base_search_bar.html' %}

{% block content %}


{% if show_info %}
   <img class="center-block" src="{{ show_info.image }}"></img>
   <h1 class="text-center">{{ show_info.show_title }}</h1>
   <p class="text-center"><strong>{{ show_info.episode_title }}</strong></p>
   <p class="text-center">Season: {{ show_info.season }}; Episode {{ show_info.episode_number }}</p>
{% endif %}

{% if countdown_timer %}
    <script src=/static/js/countdown.js></script>
    <p class="text-center" id="countdown-holder"></p>
    <script>
        var clock = document.getElementById("countdown-holder")
        , targetDate = new Date({{ countdown_timer.year }}, {{ countdown_timer.month }}, {{ countdown_timer.day }}, {{ countdown_timer.hour }}, {{ countdown_timer.minute }}, {{countdown_timer.second }});
 
        clock.innerHTML = countdown(targetDate).toString();
        setInterval(function(){
          clock.innerHTML = countdown(targetDate).toString();
        }, 1000);
    </script>
{% endif %}


{% endblock %}

tvshowcountdown/tvshow/templates/shows.html
{% extends 'base_search_bar.html' %}
{% block content %}

{% if users_shows %}
<h2>Shows in your collection:</h2>
  <ul>
  {% for show in users_shows %}
  <li><a href="{% url 'tvshow:info' show.ids.slug %}">{{ show.title }}</a></li>
  {% endfor %}
  </ul>
{% endif %}

{% endblock %}